language: go
go:
  - 1.13.x
go_import_path: code.cloudfoundry.org/cli
install:
- go get -u github.com/onsi/ginkgo/ginkgo
script:
- NODES=1 make units-full
branches:
  only:
  - main
  - travis
os:
  - linux
