name: Integration Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - v8
      - v7
    paths-ignore:
      - 'doc/**'
      - '.gitpod.yml'
      - 'README.md'
  push:
    branches:
      - main
      - v8
      - v7
      - linux-min-capi-int-test
    paths-ignore:
      - 'doc/**'
      - '.github/**'
      - '.gitpod.yml'
      - 'README.md'

permissions:
  contents: read

jobs:
  shared-values:
    name: Shared Values
    runs-on: ubuntu-latest
    outputs:
      secrets-environment: ${{ steps.set-secrets-environment.outputs.secrets-environment }}
      go-version: ${{ steps.set-go-version.outputs.go-version }}
      min-capi: ${{ steps.get-min-capi.outputs.min-capi }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: set-secrets-environment
        name: Set environment
        run: echo "::set-output name=secrets-environment::PROD"

      - id: set-go-version
        name: Parse Golang Version
        run: |
          go_version=($(grep -E '^go 1\.[[:digit:]]{1,2}' go.mod))
          echo "golang version: ${go_version[1]}"
          echo "::set-output name=go-version::${go_version[1]}"

      - id: get-min-capi
        name: Get Minimum CAPI Version
        run: |
          min_capi=($(yq .capi-version-min build_data.yml))
          echo "Minimum CAPI version: ${min_capi}"
          echo "::set-output name=min-capi::${min_capi}"

## START edge CAPI

  get-cf-env-with-edge-capi:
    name: Setup CF env with EDGE CAPI
    needs: shared-values
    uses: ./.github/workflows/cf-env-setup.yml
    with:
      environment: ${{ needs.shared-values.outputs.secrets-environment }}
      capi-version: edge
    secrets: inherit

  run-integration-tests-cf-env-with-edge-capi:
    name: Integration tests with EDGE CAPI
    needs:
      - shared-values
      - get-cf-env-with-edge-capi
    runs-on: ubuntu-latest
    environment: ${{ needs.shared-values.outputs.secrets-environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.shared-values.outputs.go-version}}
          check-latest: true
      - name: Download metadata
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.get-cf-env-with-edge-capi.outputs.environment-name }}
      - name: Install Tools
        run: |
          wget https://github.com/cloudfoundry/bosh-bootloader/releases/download/v8.4.110/bbl-v8.4.110_linux_x86-64 -P /tmp
          mv /tmp/bbl-* /usr/local/bin/bbl
          chmod +x /usr/local/bin/bbl
          bbl --version

          wget https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-7.0.1-linux-amd64 --output-document="/usr/local/bin/bosh"
          chmod +x /usr/local/bin/bosh
          bosh --version

          wget https://github.com/cloudfoundry/credhub-cli/releases/download/2.9.4/credhub-linux-2.9.4.tgz -P ~/
          tar xzvf ~/credhub-linux-2.9.4.tgz
          mv credhub /usr/local/bin/credhub
          chmod +x /usr/local/bin/credhub
          credhub --version
          rm ~/credhub-linux-2.9.4.tgz
      - name: Run Integration Tests
        run: |
          ENV=$(cat metadata.json | jq -r '.name')
          eval "$(bbl print-env --metadata-file ./metadata.json)"
          export CF_INT_PASSWORD="$(credhub get -n /bosh-$ENV/cf/cf_admin_password | bosh interpolate --path /value -)"
          export CF_INT_OIDC_USERNAME="admin-oidc"
          export CF_INT_OIDC_PASSWORD=$(credhub get -n /bosh-$ENV/cf/uaa_oidc_admin_password | bosh interpolate --path /value -)
          export CF_INT_API="https://api.${ENV}.cf-app.com"
          export CF_DIAL_TIMEOUT=15
          export CF_USERNAME=admin
          export FLAKE_ATTEMPTS=2
          export NODES=16
          go install github.com/onsi/ginkgo/ginkgo@v1.16.4

          make build
          export PATH="$(pwd)/out:$PATH"
          make integration-tests-full-ci

  unclaim-cf-env-with-edge-capi:
    name: Unclaim CF env with EDGE CAPI
    needs:
      - shared-values
      - get-cf-env-with-edge-capi
      - run-integration-tests-cf-env-with-edge-capi
    if: always()
    uses: ./.github/workflows/cf-env-unclaim.yml
    with:
      environment: ${{ needs.shared-values.outputs.secrets-environment }}
      toolsmith-env-name: ${{ needs.get-cf-env-with-edge-capi.outputs.environment-name }}
    secrets: inherit

## END edge CAPI

## START min CAPI
  get-cf-env-with-min-capi:
    name: Setup CF env with MIN CAPI
    needs: shared-values
    uses: ./.github/workflows/cf-env-setup.yml
    with:
      environment: ${{ needs.shared-values.outputs.secrets-environment }}
      capi-version: ${{ needs.shared-values.outputs.min-capi}}
    secrets: inherit

  run-integration-tests-cf-env-with-min-capi:
    name: Integration tests with MIN CAPI
    needs:
      - shared-values
      - get-cf-env-with-min-capi
    runs-on: ubuntu-latest
    environment: ${{ needs.shared-values.outputs.secrets-environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.shared-values.outputs.go-version}}
          check-latest: true
      - name: Download metadata
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.get-cf-env-with-min-capi.outputs.environment-name }}
      - name: Install Tools
        run: |
          wget https://github.com/cloudfoundry/bosh-bootloader/releases/download/v8.4.110/bbl-v8.4.110_linux_x86-64 -P /tmp
          mv /tmp/bbl-* /usr/local/bin/bbl
          chmod +x /usr/local/bin/bbl
          bbl --version

          wget https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-7.0.1-linux-amd64 --output-document="/usr/local/bin/bosh"
          chmod +x /usr/local/bin/bosh
          bosh --version

          wget https://github.com/cloudfoundry/credhub-cli/releases/download/2.9.4/credhub-linux-2.9.4.tgz -P ~/
          tar xzvf ~/credhub-linux-2.9.4.tgz
          mv credhub /usr/local/bin/credhub
          chmod +x /usr/local/bin/credhub
          credhub --version
          rm ~/credhub-linux-2.9.4.tgz
      - name: Run Integration Tests
        run: |
          ENV=$(cat metadata.json | jq -r '.name')
          eval "$(bbl print-env --metadata-file ./metadata.json)"
          export CF_INT_PASSWORD="$(credhub get -n /bosh-$ENV/cf/cf_admin_password | bosh interpolate --path /value -)"
          export CF_INT_OIDC_USERNAME="admin-oidc"
          export CF_INT_OIDC_PASSWORD=$(credhub get -n /bosh-$ENV/cf/uaa_oidc_admin_password | bosh interpolate --path /value -)
          export CF_INT_API="https://api.${ENV}.cf-app.com"
          export CF_DIAL_TIMEOUT=15
          export CF_USERNAME=admin
          export FLAKE_ATTEMPTS=2
          export NODES=16
          go install github.com/onsi/ginkgo/ginkgo@v1.16.4

          make build
          export PATH="$(pwd)/out:$PATH"
          make integration-tests-full-ci

  unclaim-cf-env-with-min-capi:
    name: Unclaim CF env with MIN CAPI
    needs:
      - shared-values
      - get-cf-env-with-min-capi
      - run-integration-tests-cf-env-with-min-capi
    if: always()
    uses: ./.github/workflows/cf-env-unclaim.yml
    with:
      environment: ${{ needs.shared-values.outputs.secrets-environment }}
      toolsmith-env-name: ${{ needs.get-cf-env-with-min-capi.outputs.environment-name }}
    secrets: inherit

## END min CAPI

## START windows  
  get-windows-cf-env-with-edge-capi:
    name: Setup CF env with EDGE CAPI for windows
    needs: shared-values
    uses: ./.github/workflows/cf-env-setup.yml
    with:
      environment: ${{ needs.shared-values.outputs.secrets-environment }}
      capi-version: edge
    secrets: inherit

  setup-windows-integration:
    name: Setup Integration Tests Windows
    needs: 
     - shared-values
     - get-windows-cf-env-with-edge-capi
    runs-on: ubuntu-latest
    environment: ${{ needs.shared-values.outputs.secrets-environment}}
    steps:
      - name: Download metadata
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.get-windows-cf-env-with-edge-capi.environment-name }} 

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: cli

      - name: Setup Integration Tests
        id: setup-windows-integration-step
        run: |
          ENV=$(cat metadata.json | jq -r '.name')
          DATA_DIR=$PWD/cf-data
          mkdir -p $DATA_DIR
          eval "$(bbl print-env --metadata-file metadata.json)"

          credhub login
          CF_INT_PASSWORD=$(credhub get -n /bosh-$ENV/cf/cf_admin_password | bosh interpolate --path /value -)
          CF_INT_OIDC_PASSWORD=$(credhub get -n /bosh-$ENV/cf/uaa_oidc_admin_password | bosh interpolate --path /value -)

          credhub get --name /bosh-$ENV/cf/router_ca | bosh interpolate - --path /value/certificate > $DATA_DIR/$ENV.router.ca

          echo "Deployed CAPI version:"
          bosh -d cf releases | grep capi

          # set -x

          # output password into a temp file for consumption by Windows
          echo $CF_INT_PASSWORD > $DATA_DIR/cf-password
          echo $CF_INT_OIDC_PASSWORD > $DATA_DIR/uaa-oidc-password

          echo "::set-output name=data::$DATA_DIR"
      - name: 'Upload CF Data'
        uses: actions/download-artifact@v3
        with:
          name: cf-windows-data
          path: ${{ steps.setup-windows-integration-step.outputs.data }}

  run-windows-integration-tests:
    name: Run Integration tests Windows 
    needs:
      - shared-values
      - get-windows-cf-env-with-edge-capi
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    environment: ${{ needs.shared-values.outputs.secrets-environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: cli
      - name: Set Up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.shared-values.outputs.go-version}}
          check-latest: true
      - name: Download metadata
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.get-windows-cf-env-with-edge-capi.environment-name }} 

      - name: Download CF data
        uses: actions/download-artifact@v3
        with:
          name: cf-windows-data 
      
      - name: Run Integration Tests
        run: cli/.github/win/integrations/integration-tests.ps1

  unclaim-cf-windows-env-with-edge-capi:
    name: Unclaim CF windows env with edge CAPI
    needs:
      - shared-values
      - get-windows-cf-env-with-edge-capi
      - run-windows-integration-tests
    if: always()
    uses: ./.github/workflows/cf-env-unclaim.yml
    with:
      environment: ${{ needs.shared-values.outputs.secrets-environment }}
      toolsmith-env-name: ${{ needs.get-windows-cf-env-with-edge-capi.outputs.environment-name }}
    secrets: inherit